# Generated by Django 5.1.1 on 2024-11-20 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pictures/default-avatar.svg', null=True, upload_to='profile_pictures/'),
        ),
    ]
