# Generated by Django 5.1.1 on 2024-11-22 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_notification_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='message',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
